2016-10-26 11:06:41,764 - teradata.udaexec - INFO - Initializing UdaExec...
2016-10-26 11:06:41,764 - teradata.udaexec - INFO - Reading config files: ['/etc/udaexec.ini: Not Found', '/Users/vro173/udaexec.ini: Not Found', '/Users/vro173/Documents/Python_programs/udaexec.ini: Not Found']
2016-10-26 11:06:41,764 - teradata.udaexec - INFO - Found run number file: "/Users/vro173/Documents/Python_programs/.runNumber"
2016-10-26 11:06:41,764 - teradata.udaexec - INFO - Cleaning up log files older than 90 days.
2016-10-26 11:06:41,764 - teradata.udaexec - INFO - Removed 0 log files.
2016-10-26 11:06:41,795 - teradata.udaexec - INFO - Checkpoint file not found: /Users/vro173/Documents/Python_programs/HelloWorld.checkpoint
2016-10-26 11:06:41,796 - teradata.udaexec - INFO - No previous checkpoint found, executing from beginning...
2016-10-26 11:06:41,796 - teradata.udaexec - INFO - Execution Details:
/********************************************************************************
 * Application Name: HelloWorld
 *          Version: 1.0
 *       Run Number: 20161026110641-26
 *             Host: acbc32a00557
 *         Platform: Darwin-15.6.0-x86_64-i386-64bit
 *          OS User: vro173
 *   Python Version: 3.5.2
 *  Python Compiler: GCC 4.2.1 Compatible Apple LLVM 4.2 (clang-425.0.28)
 *     Python Build: ('default', 'Jul  2 2016 17:52:12')
 *  UdaExec Version: 15.10.0.20
 *     Program Name: classify_tables.py
 *      Working Dir: /Users/vro173/Documents/Python_programs
 *          Log Dir: /Users/vro173/Documents/Python_programs/logs
 *         Log File: /Users/vro173/Documents/Python_programs/logs/HelloWorld.20161026110641-26.log
 *     Config Files: ['/etc/udaexec.ini: Not Found', '/Users/vro173/udaexec.ini: Not Found', '/Users/vro173/Documents/Python_programs/udaexec.ini: Not Found']
 *      Query Bands: ApplicationName=HelloWorld;Version=1.0;JobID=20161026110641-26;ClientUser=vro173;Production=False;udaAppLogFile=/Users/vro173/Documents/Python_programs/logs/HelloWorld.20161026110641-26.log;UtilityName=PyTd;UtilityVersion=15.10.0.20
********************************************************************************/
2016-10-26 11:06:41,802 - teradata.udaexec - INFO - Creating connection: {'password': 'XXXXXX', 'method': 'odbc', 'username': 'vro173', 'system': 'oneview'}
2016-10-26 11:06:41,802 - teradata.tdodbc - INFO - Loading ODBC Library: libiodbc.dylib
2016-10-26 11:06:41,807 - teradata.tdodbc - INFO - Available drivers: Amazon Redshift, MapR Drill ODBC Driver, MySQL ODBC 5.3 ANSI Driver, MySQL ODBC 5.3 Unicode Driver, PostgreSQL Unicode, Simba SQL Server ODBC Driver, Teradata
2016-10-26 11:06:48,745 - teradata.udaexec - INFO - Connection successful. Duration: 6.943 seconds. Details: {'password': 'XXXXXX', 'method': 'odbc', 'username': 'vro173', 'system': 'oneview'}
2016-10-26 11:06:53,752 - teradata.udaexec - INFO - Query Successful. Duration: 4.017 seconds, Rows: 12, Query: SELECT COLUMNNAME FROM DBC.COLUMNS where DATABASENAME='PMASTRAT_TB' AND TABLENAME = 'AND__122006';
2016-10-26 11:06:57,443 - teradata.udaexec - INFO - Query Successful. Duration: 3.674 seconds, Rows: 4, Query: SELECT COLUMNNAME FROM DBC.COLUMNS where DATABASENAME='PMASTRAT_TB' AND TABLENAME = 'AND_41789_042009';
2016-10-26 11:07:00,978 - teradata.udaexec - INFO - Query Successful. Duration: 3.528 seconds, Rows: 3, Query: SELECT COLUMNNAME FROM DBC.COLUMNS where DATABASENAME='PMASTRAT_TB' AND TABLENAME = 'AND_41789_CCB_042009';
2016-10-26 11:07:03,584 - teradata.udaexec - INFO - Query Successful. Duration: 2.593 seconds, Rows: 21, Query: SELECT COLUMNNAME FROM DBC.COLUMNS where DATABASENAME='PMASTRAT_TB' AND TABLENAME = 'AND_CAT1_AFFILIATE_122006';
2016-10-26 11:07:05,672 - teradata.udaexec - INFO - Query Successful. Duration: 2.080 seconds, Rows: 143, Query: SELECT COLUMNNAME FROM DBC.COLUMNS where DATABASENAME='PMASTRAT_TB' AND TABLENAME = 'AND_CAT1_APPLICATION_122006';
2016-10-26 11:07:13,104 - teradata.udaexec - INFO - Query Successful. Duration: 7.422 seconds, Rows: 4, Query: SELECT COLUMNNAME FROM DBC.COLUMNS where DATABASENAME='PMASTRAT_TB' AND TABLENAME = 'AND_CAT1_APR_TRNS_122006';
2016-10-26 11:07:17,508 - teradata.udaexec - INFO - Query Successful. Duration: 4.395 seconds, Rows: 12, Query: SELECT COLUMNNAME FROM DBC.COLUMNS where DATABASENAME='PMASTRAT_TB' AND TABLENAME = 'AND_CAT1_CONTACT_122006';
2016-10-26 11:07:24,882 - teradata.udaexec - INFO - Query Successful. Duration: 7.366 seconds, Rows: 3, Query: SELECT COLUMNNAME FROM DBC.COLUMNS where DATABASENAME='PMASTRAT_TB' AND TABLENAME = 'AND_CAT1_CONTACT_DISP_122006';
2016-10-26 11:07:33,074 - teradata.udaexec - ERROR - Uncaught exception
Traceback (most recent call last):
  File "classify_tables.py", line 25, in <module>
    c.execute("SELECT COLUMNNAME FROM DBC.COLUMNS where DATABASENAME='{0}' AND TABLENAME = '{1}';".format(row[0], row[1]))
  File "/Users/vro173/anaconda/lib/python3.5/site-packages/teradata/udaexec.py", line 745, in execute
    self._execute(self.cursor.execute, query, params, **kwargs)
  File "/Users/vro173/anaconda/lib/python3.5/site-packages/teradata/udaexec.py", line 790, in _execute
    func(query, params, **kwargs)
  File "/Users/vro173/anaconda/lib/python3.5/site-packages/teradata/tdodbc.py", line 591, in execute
    self.hStmt, _inputStr(_convertLineFeeds(query)), SQL_NTS)
KeyboardInterrupt
2016-10-26 11:07:33,081 - teradata.tdodbc - WARNING - 1 open connections found on exit, attempting to close...
2016-10-26 11:07:33,585 - teradata.udaexec - INFO - UdaExec exiting.
